
ALTER TABLE public.log_riprese
  ADD COLUMN IF NOT EXISTS file_id TEXT,
  ADD COLUMN IF NOT EXISTS file_url TEXT,
  ADD COLUMN IF NOT EXISTS file_name TEXT,
  ADD COLUMN IF NOT EXISTS file_size BIGINT,
  ADD COLUMN IF NOT EXISTS file_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS file_uploaded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS file_deleted_at TIMESTAMPTZ;
